#!/usr/bin/env bash

. /etc/adaptec/aac.conf

#Set script name
SCRIPT=`basename ${BASH_SOURCE[0]}`

#Defunct disk drive count                 : 1
#Logical devices/Failed/Degraded          : 2/0/1

DEGRADED=($($ARCCONF getconfig 1 ad|grep "Degraded"|cut -d: -f2|tr '/' ' '))
DEFUNCT=$($ARCCONF getconfig 1 ad|grep "Defunct disk drive count"|awk '{print $6}')
REBUILDING=$($ARCCONF getconfig 1 pd|grep -A4 Rebuilding|grep -e "Reported Location"|cut -d: -f2)

if [ ! -z "${DEGRADED[2]}" ]; then
	status="Degraded"
	if [ ! -z "$REBUILDING" ]; then
		PERCENT=$($ARCCONF getstatus 1|grep "Percentage complete"|cut -d: -f2)
		location="Rebuilding at $REBUILDING Percent complete: $PERCENT"
		exitstatus=1
	else
		STATE=$($ARCCONF getconfig 1 pd|grep -A2 Failed|egrep -e "Reported Location|*  State *: "|grep -v Failed|cut -d: -f2)
		status="Failed drive not rebuilding"
		exitstatus=2
		location=$STATE
	fi
elif [ ! -z "$DEFUNCT" -a "$DEFUNCT" -ne 0 ]; then
	STATE=$($ARCCONF getconfig 1 pd|grep -A2 Failed|egrep -e "Reported Location|*  State *: "|grep -v Failed|cut -d: -f2)
	status="Failed drive not degraded"
	exitstatus=1
	location=$STATE
else
	status="OK"
	exitstatus=0
fi

message="AACRAID $status $location"

echo -e $message
$(exit $exitstatus)
