#!/usr/bin/env bash

. /etc/adaptec/aac.conf

#Set script name
SCRIPT=`basename ${BASH_SOURCE[0]}`

#Defunct disk drive count                 : 1
#Logical devices/Failed/Degraded          : 2/0/1

DEGRADED=($($ARCCONF getconfig 1 ad|grep "Degraded"|cut -d: -f2|tr '/' ' '))
DEFUNCT=$($ARCCONF getconfig 1 ad|grep "Defunct disk drive count"|awk '{print $6}')
SMART=$($ARCCONF getconfig 1 pd|grep "S.M.A.R.T. warnings"|awk '{print $4}'|grep -v 0|wc -l)
OFFLINE=$($ARCCONF getconfig 1 pd | sed -n '/Device #/{:start /State/!{N;b start};s/\n//g;s/ *\(Device #[[:digit:]]*\).*\(State \)*:\(.*\)$/\1\2:\3/p}' | grep -v -E "(Online|Global Hot-Spare)" | wc -l)

if [ "${DEGRADED[2]}" -ne 0 ]; then
	status="Degraded"
	REBUILDING=$($ARCCONF getconfig 1 pd|grep -A4 Rebuilding|grep -e "Reported Location"|cut -d: -f2)
	if [ ! -z "$REBUILDING" ]; then
		PERCENT=$($ARCCONF getstatus 1|grep "Percentage complete"|cut -d: -f2)
		location="Rebuilding at $REBUILDING Percent complete: $PERCENT"
		exitstatus=1
	else
		STATE=$($ARCCONF getconfig 1 pd|grep -A2 Failed|egrep -e "Reported Location|*  State *: "|grep -v Failed|cut -d: -f2)
		status="Failed drive not rebuilding"
		exitstatus=2
		location=$STATE
	fi
elif [ ! -z "$DEFUNCT" -a "$DEFUNCT" -ne 0 ]; then
	STATE=$($ARCCONF getconfig 1 pd|grep -A2 Failed|egrep -e "Reported Location|*  State *: "|grep -v Failed|cut -d: -f2)
	status="Failed drive not degraded"
	exitstatus=1
	location=$STATE
elif [ "$SMART" -ne 0 ]; then
	status="$status SMART Warnings $SMART"
	exitstatus=1
elif [ "$OFFLINE" -ne 0 ]; then
	DEVICE_STATE=$($ARCCONF getconfig 1 pd | sed -n '/Device #/{:start /State/!{N;b start};s/\n//g;s/ *\(Device #[[:digit:]]*\).*\(State \)*:\(.*\)$/\1\2:\3/p}' | grep -v -E "(Online|Global Hot-Spare)")
	status="Offline"
	location=$DEVICE_STATE
	exitstatus=1
else
	status="OK"
	exitstatus=0
fi

message="AACRAID $status $location"

echo -e $message
$(exit $exitstatus)
